version: 0.2

phases:
  install:
    commands:
      - yum install -y unzip
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - terraform init
      - terraform apply -auto-approve \
          -var "region=$REGION" \
          -var "key_name=$KEY_NAME" \
          -var "instance_count=$INSTANCE_COUNT" \
          -var "install_splunk=$INSTALL_SPLUNK" \
          -var "instance_name=$INSTANCE_NAME"
artifacts:
  files:
    - "**/*"
